import { Gavel, Clock, DollarSign, FileText, AlertTriangle, CheckCircle, Mail, Scale } from 'lucide-react';

const Appeals = () => {
  return (
    <div className="page-container">
      <div className="professional-header">
        <div className="professional-header-content">
          <div className="professional-title-container">
            <div className="professional-title-icon">
              <Scale size={24} />
            </div>
            <div className="professional-title-text">
              <h1 className="professional-main-title">Appeals</h1>
              <div className="professional-title-divider"></div>
              <p className="professional-title-description">
                Understanding the appeal process for RRA decisions and assessments
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="page-content">
        {/* When Can Taxpayers Appeal Section */}
        <section className="content-section">
          <h2>When can taxpayers appeal?</h2>
          <div className="info-card">
            <div className="info-icon">
              <Gavel size={24} />
            </div>
            <div className="info-content">
              <p>
                Taxpayers may appeal to RRA against decisions within <strong>30 days</strong> following the conclusion of audits and/or receiving any assessment notices of taxes or penalties.
              </p>
              <div className="notice-box">
                <p>
                  <strong>Note:</strong> However, disputes related to a notice of assessment generated by electronic tax system based on declaration made by a taxpayer may be administratively resolved without recourse to appeal procedure.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Payment During Appeals Section */}
        <section className="content-section">
          <h2>Do taxes and fines still have to be paid when appealing?</h2>
          <div className="info-card">
            <div className="info-icon">
              <DollarSign size={24} />
            </div>
            <div className="info-content">
              <p>
                It is important to note that taxpayers are still required to pay any taxes or penalties within the original deadlines. Failure to do so will result in penalties and interest applying as normal.
              </p>
              <div className="important-notice">
                <p>
                  <strong>Important:</strong> If the appeals are successful, taxpayers will receive refunds or credit notes. However, when the taxpayer has paid the undisputed portion of the tax, the Commissioner General suspends the collection of tax that is subject of appeal.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Appeal Process Section */}
        <section className="content-section">
          <h2>What is the process, timeframe and level of appeal?</h2>
          <div className="info-card">
            <div className="info-icon">
              <Clock size={24} />
            </div>
            <div className="info-content">
              <p>
                In order to appeal, taxpayers must write a letter addressed to the Commissioner General of RRA within <strong>30 days</strong> of receiving notice of the decision they wish to appeal.
              </p>
            </div>
          </div>

          <div className="appeal-process-card">
            <h3>Appeal Letter Requirements</h3>
            <p>The appeal letter should include:</p>
            <ul className="requirements-list">
              <li>Identify the taxpayer's name and TIN</li>
              <li>Identify the tax period and tax type(s) concerned</li>
              <li>State the decision that is being appealed</li>
              <li>State the reason(s) for the appeal</li>
              <li>Contain all supporting documents, proofs and legal arguments against the assessment</li>
              <li>Be signed by the taxpayer or legal representative</li>
            </ul>
          </div>

          <div className="timeline-card">
            <h3>Appeal Timeline</h3>
            <div className="timeline-grid">
              <div className="timeline-item">
                <h4>RRA Response</h4>
                <p>RRA is required to respond to the appeal within <strong>30 days</strong></p>
              </div>
              <div className="timeline-item">
                <h4>Possible Outcomes</h4>
                <ul className="outcomes-list">
                  <li>Accept the appeal</li>
                  <li>Invite taxpayer to RRA offices for further explanation</li>
                  <li>Extend by additional 30 days and inform taxpayer</li>
                </ul>
              </div>
              <div className="timeline-item">
                <h4>If Not Satisfied</h4>
                <p>Within <strong>30 days</strong>, taxpayer may:</p>
                <ul className="outcomes-list">
                  <li>Apply for 'amicable agreement' with RRA</li>
                  <li>File case to the competent court</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* Appeal Cost Section */}
        <section className="content-section">
          <h2>What is the cost of appeal?</h2>
          <div className="info-card">
            <div className="info-icon">
              <DollarSign size={24} />
            </div>
            <div className="info-content">
              <p>
                There is <strong>no cost</strong> of appealing to RRA. However, there may be fees incurred when appealing to the Courts.
              </p>
            </div>
          </div>
        </section>

        {/* Supporting Documents Section */}
        <section className="content-section">
          <h2>What documents might be used to support an appeal?</h2>
          <div className="info-card">
            <div className="info-icon">
              <FileText size={24} />
            </div>
            <div className="info-content">
              <p>
                The types of supporting documents may vary depending upon the circumstances of the appeal, but typically include:
              </p>
              <ul className="documents-list">
                <li>Invoices</li>
                <li>Proof of payment</li>
                <li>Books of account</li>
                <li>Financial statements</li>
                <li>Similar supporting documentation</li>
              </ul>
              <div className="important-notice">
                <p>
                  <strong>Important:</strong> It is important to note any documents used to support appeals following the conclusion of audits must have also been provided at the time of the audit.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Risks Section */}
        <section className="content-section">
          <h2>Can appeals make assessments worse for the taxpayer?</h2>
          <div className="info-card">
            <div className="info-icon">
              <AlertTriangle size={24} />
            </div>
            <div className="info-content">
              <p>
                There is <strong>no penalty or fine</strong> for making unsuccessful appeals. However, appeals could potentially lead to further assessment of the case and the uncovering of new information leading to additional penalties or fines.
              </p>
            </div>
          </div>
        </section>

        {/* Important Notice Section */}
        <section className="content-section">
          <div className="notice-card warning">
            <div className="notice-icon">
              <AlertTriangle size={24} />
            </div>
            <div className="notice-content">
              <h3>Important Considerations</h3>
              <ul className="considerations-list">
                <li>Ensure all supporting documents are complete and accurate</li>
                <li>Pay undisputed portions of tax to avoid additional penalties</li>
                <li>Keep copies of all correspondence and documentation</li>
                <li>Consider seeking professional advice for complex appeals</li>
                <li>Be aware that appeals may lead to further investigation</li>
              </ul>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};

export default Appeals;
